### PR TITLE
Debug log when preprocessor for a locale is missing (instead of crashing)

### PR DESCRIPTION
**Pull request by Gregoor**
I thought that might be a nicer experience for when new locales are added.

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
Just wondering if this is a better or worse experience.

Before if there was a missing preprocessor this code crashed and didn't continue at all. Now, it prints a log message, which might be ignored, and simply copies the sentences as is.

In theory, and in practice, this code should be used only on the alpha clips.tsv which we are in complete control of. So if there is a missing preprocessor, it's our fault. A crash will let us and other users know right away there is a problem and a crash can't be as easily missed.

**Comment by Gregoor** [comment]
Fair enough!

**Comment by Gregoor** [comment]
@kdavis-mozilla we might want to revisit this. My reasoning is: I'd want the common voice data bundler to run without human intervention. Since its depending on the CorporaCreator to know about all the languages, it fails anytime we're missing a language here. A possible compromise: Have warning instead of error be a flag we can pass to the CLI, that way the default behavior would still be like you want it, but for the bundler it could run through without intervention.

**Comment by kdavis-mozilla** [comment]
I worry that this is basically an invitation for no checking of the text + audio.

**Comment by Gregoor** [comment]
I do share that worry, but I don't think an empty preprocessor file is a replacement for a process here. I guess what we would want is to bring people who have feedback about sentence quality into this repository to contribute to their language's preprocessor. Maybe we could make it part of our release comms to point to this repo?

**Comment by kdavis-mozilla** [comment]
As far as I understand it there is no "release comms" on the next release. New languages will just appear in the Datasets Page's dropdown. So there's no process in place that will fix this.

Also another point is that if the releases are made, then they are subsequently fixed, the data sets are significantly less useful for academics and they publish results like, "Such and such word error rate  on Common Voice 7.0". In our case 7.0 may be a release with data that's of very little use.

**Comment by kdavis-mozilla** [comment]
I should say currently I don't think it will make a big difference if we add or don't add this change to the code as there's no process in place to draw people here to help fix things.

**Pull request closed without merging**
