### PR TITLE
removed unnecessary quotationmarks from de-lang sentences

### PR DESCRIPTION
**Pull request by simnotes**
Noticed multiple strange cases of sentences containing a lot of quotation marks in reoccurring patters in german language corpus.

Patterns found:

- """content""content."
- "content""content""content."
- "content."

Examples

- """Beim Wrestling ist alles nur Show"", behauptet Willi."
- "Das Prinzip heißt ""teile und herrsche""."
- "Probier's mal mit Gemütlichkeit!"

Only checked the french corpus as well, the problem did not seem to occur in it. So applied the fix in the de.py preprocessor. (Although I did not check any other language corpus, so your mileage may vary.)

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
Are you sure that some of these examples

> "Das Prinzip heißt ""teile und herrsche""."

shouldn't be fixed as

> Das Prinzip heißt „teile und herrsche".

or maybe

> Das Prinzip heißt «teile und herrsche».

**Comment by simnotes** [comment]
I gave it a good long thought... in my opinion the only valid options are:
> 
> > Das Prinzip heißt „teile und herrsche".
> 
or 
> 
> > Das Prinzip heißt teile und herrsche.
> 

The first one is probably the spelling-wise correct version, but in the case of training a neural network for speech-to-text and other tasks I probably would use the second one as input, since the quotationmarks won't actually be spoken/pronounced. So it depends - if the main use of Common Voice Project is giving ppl a good dataset for training models on, I'd use the second one. In every other case, I'd use the first one. What do you think?

**Comment by kdavis-mozilla** [comment]
For speech to text I think it's currently hard for an engine to place quotes in the correct position. However, I don't think it's out of the realm of possibility for an engine to place quotes correctly in the near future, one to two years. (Actually I'd be surprised if its not possible in research code now.)

The logic of keeping the quotes in is that it future proofs the data set, allowing it to be of use now and in future.

One further question: Why do you think guillemets are never valid in German? Or are you only talking about the direction of the guillemets?

**Comment by kdavis-mozilla** [comment]
Just grepped through the currently generated German csv's and found no guillemets, « and », or single guillemets, ‹ and ›. So the extra PR will no be required.

**Comment by simnotes** [comment]
Will incorporate the requested changes tomorrow so that conversion will be like 
>
> Das Prinzip heißt „teile und herrsche“. 
>

As for the guillemets I found in the german book Duden (which is the standard refernce for german spelling and grammar, that only inverted guillements like »…« are accepted, but those are only used in novel writing and nowhere else used. So since CV is about spoken language, there should not be any »…« in the dataset.

**Comment by simnotes** [comment]
Ok, I think now the changes are ready to be merged with master :smile:

**Comment by kdavis-mozilla** [comment]
> So... maybe I make one more change to my PR and we resolve it to be like the last example?

This sounds good to me

Nice catch on the switch from

```python
dataframe.to_csv(
  path, sep="\t", header=True, index=False, encoding="utf-8", escapechar='"'
)
```

to

```python
dataframe.to_csv(
  path, sep="\t", header=True, index=False, encoding="utf-8", escapechar='\\', quoting=csv.QUOTE_NONE
)
```

I can add another PR with this change. I'll ask for your review.

**Comment by simnotes** [comment]
I think we are done here :smile:

**Pull request merged**
